version: '3.8'

services:
  back-ventas:
    build:
      context: ./back-ventas
    container_name: api-ventas
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: ${DB_HOST_IP:-host.docker.internal}
      DB_PORT: 3306
      DB_NAME: ventas_db
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
    restart: unless-stopped

  back-despachos:
    build:
      context: ./back-despachos
    container_name: api-despachos
    ports:
      - "8081:8081"
    environment:
      DB_ENDPOINT: ${DB_HOST_IP:-host.docker.internal}
      DB_PORT: 3306
      DB_NAME: despacho_db
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
    restart: unless-stopped